// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestingInADO.Data;

namespace TestingInADO.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestingInADO.Models.MovieModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.HasIndex("Title");

                    b.HasIndex("Year");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Minions",
                            Year = 2015
                        },
                        new
                        {
                            Id = 2,
                            Title = "Big Hero 6",
                            Year = 2014
                        },
                        new
                        {
                            Id = 3,
                            Title = "Rio 2 - Missione Amazzonia",
                            Year = 2014
                        },
                        new
                        {
                            Id = 4,
                            Title = "Frozen - Il Regno di Ghiaccio",
                            Year = 2013
                        },
                        new
                        {
                            Id = 5,
                            Title = "Monsters University",
                            Year = 2013
                        },
                        new
                        {
                            Id = 6,
                            Title = "Cattivissimo Me 2",
                            Year = 2013
                        },
                        new
                        {
                            Id = 7,
                            Title = "I Croodz",
                            Year = 2013
                        },
                        new
                        {
                            Id = 8,
                            Title = "Epic - Il mondo segreto",
                            Year = 2013
                        },
                        new
                        {
                            Id = 9,
                            Title = "Planes",
                            Year = 2013
                        },
                        new
                        {
                            Id = 10,
                            Title = "Si alza il vento",
                            Year = 2013
                        },
                        new
                        {
                            Id = 11,
                            Title = "Ribelle - The Brave",
                            Year = 2012
                        },
                        new
                        {
                            Id = 12,
                            Title = "Le 5 leggende",
                            Year = 2012
                        },
                        new
                        {
                            Id = 13,
                            Title = "L'era glaciale 4 - Continenti alla deriva",
                            Year = 2012
                        },
                        new
                        {
                            Id = 14,
                            Title = "Madagascar 3: Ricercati in Europa",
                            Year = 2012
                        },
                        new
                        {
                            Id = 15,
                            Title = "Cars 2",
                            Year = 2011
                        },
                        new
                        {
                            Id = 16,
                            Title = "Kung Fu Panda 2",
                            Year = 2011
                        },
                        new
                        {
                            Id = 17,
                            Title = "Il gatto con gli stivali",
                            Year = 2011
                        },
                        new
                        {
                            Id = 18,
                            Title = "Rio",
                            Year = 2011
                        },
                        new
                        {
                            Id = 19,
                            Title = "Cattivissimo Me",
                            Year = 2010
                        },
                        new
                        {
                            Id = 20,
                            Title = "Toy Story 3 - La grande fuga",
                            Year = 2010
                        },
                        new
                        {
                            Id = 21,
                            Title = "Rapunzel - L'Intreccio della Torre",
                            Year = 2010
                        },
                        new
                        {
                            Id = 22,
                            Title = "Shrek e vissero felici e contenti",
                            Year = 2010
                        },
                        new
                        {
                            Id = 23,
                            Title = "Le avventure di Sammy",
                            Year = 2010
                        },
                        new
                        {
                            Id = 24,
                            Title = "Arrietty",
                            Year = 2010
                        },
                        new
                        {
                            Id = 25,
                            Title = "L'era glaciale 3 - L'alba dei dinosauri",
                            Year = 2009
                        },
                        new
                        {
                            Id = 26,
                            Title = "La Principessa e il Ranocchio",
                            Year = 2009
                        },
                        new
                        {
                            Id = 27,
                            Title = "Piovono gnocchi",
                            Year = 2009
                        },
                        new
                        {
                            Id = 28,
                            Title = "Kung Fu Panda",
                            Year = 2008
                        },
                        new
                        {
                            Id = 29,
                            Title = "Madagascar 2",
                            Year = 2008
                        },
                        new
                        {
                            Id = 30,
                            Title = "Ponyo sulla scogliera",
                            Year = 2008
                        },
                        new
                        {
                            Id = 31,
                            Title = "Ratatouille",
                            Year = 2007
                        },
                        new
                        {
                            Id = 32,
                            Title = "Shrek terzo",
                            Year = 2007
                        },
                        new
                        {
                            Id = 33,
                            Title = "Il viaggio di Arlo",
                            Year = 2015
                        },
                        new
                        {
                            Id = 34,
                            Title = "Zootropolis",
                            Year = 2016
                        },
                        new
                        {
                            Id = 35,
                            Title = "Oceania",
                            Year = 2016
                        },
                        new
                        {
                            Id = 36,
                            Title = "Your Name",
                            Year = 2016
                        },
                        new
                        {
                            Id = 37,
                            Title = "Ballerina",
                            Year = 2016
                        },
                        new
                        {
                            Id = 38,
                            Title = "Coco",
                            Year = 2017
                        },
                        new
                        {
                            Id = 39,
                            Title = "Cars 3",
                            Year = 2017
                        },
                        new
                        {
                            Id = 40,
                            Title = "Cattivissimo Me 3",
                            Year = 2017
                        },
                        new
                        {
                            Id = 41,
                            Title = "Sherlock Gnomes",
                            Year = 2018
                        },
                        new
                        {
                            Id = 42,
                            Title = "Il Grinch",
                            Year = 2018
                        },
                        new
                        {
                            Id = 43,
                            Title = "I Primitivi",
                            Year = 2018
                        });
                });

            modelBuilder.Entity("TestingInADO.Models.RatingComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MovieId");

                    b.Property<int>("Value");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MovieId = 1,
                            Value = 5
                        },
                        new
                        {
                            Id = 2,
                            MovieId = 1,
                            Value = 4
                        },
                        new
                        {
                            Id = 3,
                            MovieId = 1,
                            Value = 3
                        },
                        new
                        {
                            Id = 4,
                            MovieId = 1,
                            Value = 2
                        },
                        new
                        {
                            Id = 5,
                            MovieId = 2,
                            Value = 5
                        },
                        new
                        {
                            Id = 6,
                            MovieId = 2,
                            Value = 3
                        },
                        new
                        {
                            Id = 7,
                            MovieId = 2,
                            Value = 5
                        },
                        new
                        {
                            Id = 8,
                            MovieId = 2,
                            Value = 2
                        },
                        new
                        {
                            Id = 9,
                            MovieId = 3,
                            Value = 3
                        },
                        new
                        {
                            Id = 10,
                            MovieId = 3,
                            Value = 4
                        },
                        new
                        {
                            Id = 11,
                            MovieId = 3,
                            Value = 3
                        },
                        new
                        {
                            Id = 12,
                            MovieId = 4,
                            Value = 1
                        },
                        new
                        {
                            Id = 13,
                            MovieId = 4,
                            Value = 5
                        },
                        new
                        {
                            Id = 14,
                            MovieId = 4,
                            Value = 5
                        },
                        new
                        {
                            Id = 15,
                            MovieId = 4,
                            Value = 4
                        },
                        new
                        {
                            Id = 16,
                            MovieId = 5,
                            Value = 5
                        },
                        new
                        {
                            Id = 17,
                            MovieId = 5,
                            Value = 5
                        },
                        new
                        {
                            Id = 18,
                            MovieId = 5,
                            Value = 5
                        },
                        new
                        {
                            Id = 19,
                            MovieId = 6,
                            Value = 4
                        },
                        new
                        {
                            Id = 20,
                            MovieId = 6,
                            Value = 3
                        },
                        new
                        {
                            Id = 21,
                            MovieId = 6,
                            Value = 5
                        },
                        new
                        {
                            Id = 22,
                            MovieId = 7,
                            Value = 3
                        },
                        new
                        {
                            Id = 23,
                            MovieId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 24,
                            MovieId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 25,
                            MovieId = 7,
                            Value = 3
                        },
                        new
                        {
                            Id = 26,
                            MovieId = 8,
                            Value = 5
                        },
                        new
                        {
                            Id = 27,
                            MovieId = 8,
                            Value = 4
                        },
                        new
                        {
                            Id = 28,
                            MovieId = 8,
                            Value = 4
                        },
                        new
                        {
                            Id = 29,
                            MovieId = 9,
                            Value = 2
                        },
                        new
                        {
                            Id = 30,
                            MovieId = 9,
                            Value = 2
                        },
                        new
                        {
                            Id = 31,
                            MovieId = 9,
                            Value = 5
                        },
                        new
                        {
                            Id = 32,
                            MovieId = 10,
                            Value = 4
                        },
                        new
                        {
                            Id = 33,
                            MovieId = 10,
                            Value = 1
                        },
                        new
                        {
                            Id = 34,
                            MovieId = 10,
                            Value = 2
                        },
                        new
                        {
                            Id = 35,
                            MovieId = 10,
                            Value = 5
                        },
                        new
                        {
                            Id = 36,
                            MovieId = 11,
                            Value = 2
                        },
                        new
                        {
                            Id = 37,
                            MovieId = 11,
                            Value = 3
                        },
                        new
                        {
                            Id = 38,
                            MovieId = 11,
                            Value = 1
                        },
                        new
                        {
                            Id = 39,
                            MovieId = 11,
                            Value = 2
                        },
                        new
                        {
                            Id = 40,
                            MovieId = 12,
                            Value = 4
                        },
                        new
                        {
                            Id = 41,
                            MovieId = 12,
                            Value = 4
                        },
                        new
                        {
                            Id = 42,
                            MovieId = 12,
                            Value = 3
                        },
                        new
                        {
                            Id = 43,
                            MovieId = 13,
                            Value = 5
                        },
                        new
                        {
                            Id = 44,
                            MovieId = 13,
                            Value = 5
                        },
                        new
                        {
                            Id = 45,
                            MovieId = 13,
                            Value = 4
                        },
                        new
                        {
                            Id = 46,
                            MovieId = 14,
                            Value = 4
                        },
                        new
                        {
                            Id = 47,
                            MovieId = 14,
                            Value = 4
                        },
                        new
                        {
                            Id = 48,
                            MovieId = 14,
                            Value = 2
                        },
                        new
                        {
                            Id = 49,
                            MovieId = 14,
                            Value = 5
                        },
                        new
                        {
                            Id = 50,
                            MovieId = 15,
                            Value = 1
                        },
                        new
                        {
                            Id = 51,
                            MovieId = 15,
                            Value = 5
                        },
                        new
                        {
                            Id = 52,
                            MovieId = 15,
                            Value = 1
                        },
                        new
                        {
                            Id = 53,
                            MovieId = 15,
                            Value = 4
                        },
                        new
                        {
                            Id = 54,
                            MovieId = 16,
                            Value = 2
                        },
                        new
                        {
                            Id = 55,
                            MovieId = 16,
                            Value = 5
                        },
                        new
                        {
                            Id = 56,
                            MovieId = 16,
                            Value = 3
                        },
                        new
                        {
                            Id = 57,
                            MovieId = 16,
                            Value = 4
                        },
                        new
                        {
                            Id = 58,
                            MovieId = 17,
                            Value = 5
                        },
                        new
                        {
                            Id = 59,
                            MovieId = 17,
                            Value = 1
                        },
                        new
                        {
                            Id = 60,
                            MovieId = 17,
                            Value = 4
                        },
                        new
                        {
                            Id = 61,
                            MovieId = 17,
                            Value = 4
                        },
                        new
                        {
                            Id = 62,
                            MovieId = 18,
                            Value = 5
                        },
                        new
                        {
                            Id = 63,
                            MovieId = 18,
                            Value = 1
                        },
                        new
                        {
                            Id = 64,
                            MovieId = 18,
                            Value = 3
                        },
                        new
                        {
                            Id = 65,
                            MovieId = 19,
                            Value = 2
                        },
                        new
                        {
                            Id = 66,
                            MovieId = 19,
                            Value = 4
                        },
                        new
                        {
                            Id = 67,
                            MovieId = 19,
                            Value = 3
                        },
                        new
                        {
                            Id = 68,
                            MovieId = 19,
                            Value = 5
                        },
                        new
                        {
                            Id = 69,
                            MovieId = 20,
                            Value = 4
                        },
                        new
                        {
                            Id = 70,
                            MovieId = 20,
                            Value = 4
                        },
                        new
                        {
                            Id = 71,
                            MovieId = 20,
                            Value = 5
                        },
                        new
                        {
                            Id = 72,
                            MovieId = 20,
                            Value = 2
                        },
                        new
                        {
                            Id = 73,
                            MovieId = 21,
                            Value = 4
                        },
                        new
                        {
                            Id = 74,
                            MovieId = 21,
                            Value = 2
                        },
                        new
                        {
                            Id = 75,
                            MovieId = 21,
                            Value = 2
                        },
                        new
                        {
                            Id = 76,
                            MovieId = 21,
                            Value = 5
                        },
                        new
                        {
                            Id = 77,
                            MovieId = 22,
                            Value = 1
                        },
                        new
                        {
                            Id = 78,
                            MovieId = 22,
                            Value = 1
                        },
                        new
                        {
                            Id = 79,
                            MovieId = 22,
                            Value = 4
                        },
                        new
                        {
                            Id = 80,
                            MovieId = 23,
                            Value = 4
                        },
                        new
                        {
                            Id = 81,
                            MovieId = 23,
                            Value = 5
                        },
                        new
                        {
                            Id = 82,
                            MovieId = 23,
                            Value = 2
                        },
                        new
                        {
                            Id = 83,
                            MovieId = 23,
                            Value = 5
                        },
                        new
                        {
                            Id = 84,
                            MovieId = 24,
                            Value = 5
                        },
                        new
                        {
                            Id = 85,
                            MovieId = 24,
                            Value = 4
                        },
                        new
                        {
                            Id = 86,
                            MovieId = 24,
                            Value = 1
                        },
                        new
                        {
                            Id = 87,
                            MovieId = 25,
                            Value = 1
                        },
                        new
                        {
                            Id = 88,
                            MovieId = 25,
                            Value = 4
                        },
                        new
                        {
                            Id = 89,
                            MovieId = 25,
                            Value = 5
                        },
                        new
                        {
                            Id = 90,
                            MovieId = 26,
                            Value = 1
                        },
                        new
                        {
                            Id = 91,
                            MovieId = 26,
                            Value = 4
                        },
                        new
                        {
                            Id = 92,
                            MovieId = 26,
                            Value = 3
                        },
                        new
                        {
                            Id = 93,
                            MovieId = 27,
                            Value = 4
                        },
                        new
                        {
                            Id = 94,
                            MovieId = 27,
                            Value = 1
                        },
                        new
                        {
                            Id = 95,
                            MovieId = 27,
                            Value = 2
                        },
                        new
                        {
                            Id = 96,
                            MovieId = 28,
                            Value = 1
                        },
                        new
                        {
                            Id = 97,
                            MovieId = 28,
                            Value = 2
                        },
                        new
                        {
                            Id = 98,
                            MovieId = 28,
                            Value = 4
                        },
                        new
                        {
                            Id = 99,
                            MovieId = 28,
                            Value = 5
                        },
                        new
                        {
                            Id = 100,
                            MovieId = 29,
                            Value = 2
                        },
                        new
                        {
                            Id = 101,
                            MovieId = 29,
                            Value = 3
                        },
                        new
                        {
                            Id = 102,
                            MovieId = 29,
                            Value = 2
                        },
                        new
                        {
                            Id = 103,
                            MovieId = 29,
                            Value = 3
                        },
                        new
                        {
                            Id = 104,
                            MovieId = 30,
                            Value = 1
                        },
                        new
                        {
                            Id = 105,
                            MovieId = 30,
                            Value = 2
                        },
                        new
                        {
                            Id = 106,
                            MovieId = 30,
                            Value = 3
                        },
                        new
                        {
                            Id = 107,
                            MovieId = 30,
                            Value = 5
                        },
                        new
                        {
                            Id = 108,
                            MovieId = 31,
                            Value = 1
                        },
                        new
                        {
                            Id = 109,
                            MovieId = 31,
                            Value = 4
                        },
                        new
                        {
                            Id = 110,
                            MovieId = 31,
                            Value = 3
                        },
                        new
                        {
                            Id = 111,
                            MovieId = 31,
                            Value = 5
                        },
                        new
                        {
                            Id = 112,
                            MovieId = 32,
                            Value = 4
                        },
                        new
                        {
                            Id = 113,
                            MovieId = 32,
                            Value = 4
                        },
                        new
                        {
                            Id = 114,
                            MovieId = 32,
                            Value = 5
                        },
                        new
                        {
                            Id = 115,
                            MovieId = 33,
                            Value = 3
                        },
                        new
                        {
                            Id = 116,
                            MovieId = 33,
                            Value = 1
                        },
                        new
                        {
                            Id = 117,
                            MovieId = 33,
                            Value = 1
                        },
                        new
                        {
                            Id = 118,
                            MovieId = 33,
                            Value = 4
                        },
                        new
                        {
                            Id = 119,
                            MovieId = 34,
                            Value = 5
                        },
                        new
                        {
                            Id = 120,
                            MovieId = 34,
                            Value = 3
                        },
                        new
                        {
                            Id = 121,
                            MovieId = 34,
                            Value = 1
                        },
                        new
                        {
                            Id = 122,
                            MovieId = 35,
                            Value = 5
                        },
                        new
                        {
                            Id = 123,
                            MovieId = 35,
                            Value = 3
                        },
                        new
                        {
                            Id = 124,
                            MovieId = 35,
                            Value = 4
                        },
                        new
                        {
                            Id = 125,
                            MovieId = 36,
                            Value = 5
                        },
                        new
                        {
                            Id = 126,
                            MovieId = 36,
                            Value = 1
                        },
                        new
                        {
                            Id = 127,
                            MovieId = 36,
                            Value = 3
                        },
                        new
                        {
                            Id = 128,
                            MovieId = 36,
                            Value = 1
                        },
                        new
                        {
                            Id = 129,
                            MovieId = 37,
                            Value = 4
                        },
                        new
                        {
                            Id = 130,
                            MovieId = 37,
                            Value = 3
                        },
                        new
                        {
                            Id = 131,
                            MovieId = 37,
                            Value = 3
                        },
                        new
                        {
                            Id = 132,
                            MovieId = 37,
                            Value = 4
                        },
                        new
                        {
                            Id = 133,
                            MovieId = 38,
                            Value = 2
                        },
                        new
                        {
                            Id = 134,
                            MovieId = 38,
                            Value = 1
                        },
                        new
                        {
                            Id = 135,
                            MovieId = 38,
                            Value = 3
                        },
                        new
                        {
                            Id = 136,
                            MovieId = 38,
                            Value = 3
                        },
                        new
                        {
                            Id = 137,
                            MovieId = 39,
                            Value = 1
                        },
                        new
                        {
                            Id = 138,
                            MovieId = 39,
                            Value = 2
                        },
                        new
                        {
                            Id = 139,
                            MovieId = 39,
                            Value = 1
                        },
                        new
                        {
                            Id = 140,
                            MovieId = 40,
                            Value = 3
                        },
                        new
                        {
                            Id = 141,
                            MovieId = 40,
                            Value = 1
                        },
                        new
                        {
                            Id = 142,
                            MovieId = 40,
                            Value = 2
                        },
                        new
                        {
                            Id = 143,
                            MovieId = 41,
                            Value = 2
                        },
                        new
                        {
                            Id = 144,
                            MovieId = 41,
                            Value = 5
                        },
                        new
                        {
                            Id = 145,
                            MovieId = 41,
                            Value = 1
                        },
                        new
                        {
                            Id = 146,
                            MovieId = 41,
                            Value = 3
                        },
                        new
                        {
                            Id = 147,
                            MovieId = 42,
                            Value = 5
                        },
                        new
                        {
                            Id = 148,
                            MovieId = 42,
                            Value = 1
                        },
                        new
                        {
                            Id = 149,
                            MovieId = 42,
                            Value = 4
                        },
                        new
                        {
                            Id = 150,
                            MovieId = 42,
                            Value = 2
                        },
                        new
                        {
                            Id = 151,
                            MovieId = 43,
                            Value = 3
                        },
                        new
                        {
                            Id = 152,
                            MovieId = 43,
                            Value = 4
                        },
                        new
                        {
                            Id = 153,
                            MovieId = 43,
                            Value = 2
                        },
                        new
                        {
                            Id = 154,
                            MovieId = 43,
                            Value = 3
                        });
                });

            modelBuilder.Entity("TestingInADO.Models.RatingComponent", b =>
                {
                    b.HasOne("TestingInADO.Models.MovieModel", "Movie")
                        .WithMany("Ratings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
